// <auto-generated />
using System;
using KregulecApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KregulecApp.Migrations
{
    [DbContext(typeof(KregulecDatabaseContext))]
    partial class KregulecDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConventionInventory", b =>
                {
                    b.Property<string>("ConventionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.HasKey("ConventionName", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("ConventionInventory");
                });

            modelBuilder.Entity("GameCatalogTags", b =>
                {
                    b.Property<string>("GameCatalogsTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TagsName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GameCatalogsTitle", "TagsName");

                    b.HasIndex("TagsName");

                    b.ToTable("GameCatalogTags");
                });

            modelBuilder.Entity("KregulecApp.Model.Convention", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Nazwa");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Zakonczenia");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lokalizacja");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Rozpoczecia");

                    b.HasKey("Name");

                    b.ToTable("Conventions");
                });

            modelBuilder.Entity("KregulecApp.Model.GameCatalog", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Tytul");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Wiek");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Jezyk");

                    b.Property<TimeSpan>("PlayTime")
                        .HasColumnType("time")
                        .HasColumnName("Czas_Gry");

                    b.Property<int>("Players")
                        .HasColumnType("int")
                        .HasColumnName("Liczba_Graczy");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Wydawca");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Wydania");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("GameCatalogs");
                });

            modelBuilder.Entity("KregulecApp.Model.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completeness")
                        .HasColumnType("bit")
                        .HasColumnName("Kompletnosc");

                    b.Property<string>("GameCatalogTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gra");

                    b.Property<string>("KnownMissingParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Brakujace_Czesci");

                    b.Property<bool>("Mark")
                        .HasColumnType("bit")
                        .HasColumnName("Oznaczenie");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rzadkosc");

                    b.HasKey("Id");

                    b.HasIndex("GameCatalogTitle");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("KregulecApp.Model.Tags", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nazwa");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Opis");

                    b.HasKey("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ConventionInventory", b =>
                {
                    b.HasOne("KregulecApp.Model.Convention", null)
                        .WithMany()
                        .HasForeignKey("ConventionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KregulecApp.Model.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameCatalogTags", b =>
                {
                    b.HasOne("KregulecApp.Model.GameCatalog", null)
                        .WithMany()
                        .HasForeignKey("GameCatalogsTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KregulecApp.Model.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KregulecApp.Model.Inventory", b =>
                {
                    b.HasOne("KregulecApp.Model.GameCatalog", "GameCatalog")
                        .WithMany("Inventory")
                        .HasForeignKey("GameCatalogTitle");

                    b.Navigation("GameCatalog");
                });

            modelBuilder.Entity("KregulecApp.Model.GameCatalog", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
